feat: migrations setup

diff --git a/core/Makefile b/core/Makefile
--- a/core/Makefile
+++ b/core/Makefile
@@ -1,27 +1,28 @@
+# Database and Migration Commands
+MIGRATE_BIN = ~/go/bin/migrate
+DB_URL = "sqlite3://test.db"
+MIGRATIONS_DIR = internal/db/migrations
 
-hello:
-	echo "Hello MakeFile is working brotheeerrr"
+migrate-create:
+	@if [ -z "$(name)" ]; then \
+		echo "Name is required"; \
+		exit 1; \
+	fi
+	$(MIGRATE_BIN) create -ext sql -dir $(MIGRATIONS_DIR) -seq $(name)
+
+migrate-up:
+	$(MIGRATE_BIN) -path $(MIGRATIONS_DIR) -database $(DB_URL) up
+
+migrate-down:
+	$(MIGRATE_BIN) -path $(MIGRATIONS_DIR) -database $(DB_URL) down
+
+sqlc:
+	~/go/bin/sqlc generate
 
 api: 
 	go build -o api ./cmd/api
 
-
 bootstrap: 
 	go build -o bootstrap-script ./cmd/bootstrap
 
-watch-api:
-	air -c .air.api.toml
-
-watch-bootstrap:
-	air -c .air.bootstrap.toml
-
-# the default ip is the local ip for testing purposes 
-IP ?= 192.168.1.69
-deploy:
-	scp ./bootstrap-script ./config.json ./api ubuntu@$(IP):/home/ubuntu
-
-# WARN: This is only workks for the local
-apideploy:
-	go build -o api ./cmd/api/
-	scp ./api ironman@$(IP):/home/ironman
 
